[build]
  # Carpeta donde están tus funciones
  functions = "netlify/functions"
  publish = "dist"  # o tu carpeta de salida del build

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    # Para evitar que el navegador use versiones cacheadas
    Cache-Control = "no-cache, no-store, must-revalidate"