[build]
  functions = "netlify/functions"
  command = "mkdir dist && npm install && cp -r public/* dist/ && cp index.html dist/"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "https://eet172.infinityfreeapp.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
